### ISSUE TITLE
New PyCharm version soon to be released on pi-apps

### ISSUE THREAD

**Issue by Botspot** [gam3t3chelectronicshobbyhouse/PyCharmInstaller#1]
You may be interested to know that Pycharm on Pi-Apps will be updated soon.
Below is the beta app, for testing: https://github.com/Botspot/pi-apps/issues/926#issuecomment-903023438

**Comment by gam3t3chelectronicshobbyhouse** [comment]
Great job keeping it going will certainly help a lot of people enjoying Pycharm.  I have been keeping it updated on https://github.com/gam3t3chelectronicshobbyhouse/PyCharmInstaller   which I will continue to maintain so if you need to pull from there to help out feel free to update through it.  I update and double check all updates every time its updated with new and upgrade installs.

**Comment by Botspot** [comment]
> Great job keeping it going will certainly help a lot of people enjoying Pycharm.

As there were no bug reports for the beta testing zip I posted, I have gone ahead and pushed the update to all Pi-Apps installations.

This appears to have worried at least one github user over there as they say the 2018 version of Pycharm is the last "good" version for 32-bit. Would you mind sharing your thoughts on the subject there?
Link: `https://github.com/Botspot/pi-apps/issues/924#issuecomment-903323526`

**Comment by cycool29** [comment]
Why not update to 2021.2.1 version?

I tested by changing the `downloadlink` variable in the current Pycharm CE install script to https://download-cf.jetbrains.com/python/pycharm-community-2021.2.1.tar.gz and removing `sudo mkdir /opt/$name/lib/pty4j-native/linux/arm || error "Failed to make directory /opt/$name/lib/pty4j-native/linux/arm"` from the script as I met this error when installing: `Failed to make directory /opt/pycharm-community/lib/pty4j-native/linux/arm`.

Pycharm installed successfully and runs well for a week.

**Comment by gam3t3chelectronicshobbyhouse** [comment]
I did update the 2021.2.1 installer script but no errors like you were having so if continues will investigate further.    So if anyone has this issue please post about it.

**Comment by Botspot** [comment]
[Pi-Apps has been updated](https://github.com/Botspot/pi-apps/commit/1bc0d07b3cca604ffccbcc29d217c75655bf2cbe) to use Pycharm version 2021.2.1.
